/**
 * Master city sequence along the Palanpur → Mumbai corridor (NH-48 / Gujarat SH).
 * Cities are in PHYSICAL order. `km` = cumulative distance from Palanpur (used as `halts`).
 * When a bus runs from city A to city B, all cities between A and B are intermediate stops.
 */
const CITY_ROUTE = [
  { city: "Palanpur",          km: 0   },
  { city: "Deodar",            km: 30  },
  { city: "Deesa",             km: 56  },
  { city: "Dhanera",           km: 72  },
  { city: "Patan",             km: 90  },
  { city: "Sidhpur",           km: 108 },
  { city: "Unjha",             km: 118 },
  { city: "Mahesana",          km: 138 },
  { city: "Visnagar",          km: 150 },
  { city: "Kadi",              km: 162 },
  { city: "Kalol",             km: 174 },
  { city: "Gandhinagar",       km: 186 },
  { city: "Ahmedabad",         km: 200 },
  { city: "Narol",             km: 212 },
  { city: "Bavla",             km: 226 },
  { city: "Dholka",            km: 240 },
  { city: "Bagodara",          km: 256 },
  { city: "Nadiad",            km: 272 },
  { city: "Anand",             km: 288 },
  { city: "Karamsad",          km: 298 },
  { city: "Vallabh Vidyanagar",km: 306 },
  { city: "Vadodara",          km: 326 },
  { city: "Padra",             km: 340 },
  { city: "Jambusar",          km: 362 },
  { city: "Ankleshwar",        km: 384 },
  { city: "Bharuch",           km: 395 },
  { city: "Palej",             km: 408 },
  { city: "Surat",             km: 445 },
  { city: "Bardoli",           km: 464 },
  { city: "Navsari",           km: 480 },
  { city: "Bilimora",          km: 496 },
  { city: "Chikhli",           km: 510 },
  { city: "Gandevi",           km: 522 },
  { city: "Valsad",            km: 536 },
  { city: "Pardi",             km: 550 },
  { city: "Vapi",              km: 562 },
  { city: "Umargam",           km: 574 },
  { city: "Dharampur",         km: 592 },
  { city: "Palghar",           km: 618 },
  { city: "Boisar",            km: 632 },
  { city: "Virar",             km: 650 },
  { city: "Vasai",             km: 662 },
  { city: "Nalasopara",        km: 670 },
  { city: "Mira Road",         km: 682 },
  { city: "Thane",             km: 700 },
  { city: "Mumbai",            km: 750 },
];

module.exports = CITY_ROUTE;
